### ISSUE TITLE
Support setting of streams from R 

### ISSUE THREAD

**Issue by LTLA** [daqana/dqrng#19]
I was answering a question on the Bioconductor mailing list (see [here](https://stat.ethz.ch/pipermail/bioc-devel/2019-March/014755.html)) and it occurred to me that it would be nice to be able to set the stream from R in parallel applications. Sort of like what I've been doing in my code, but without requiring people to write C++. Maybe a `dqset.stream` for those generators that support it, which would allow non-C++ users to take advantage of a key selling point of the PCG family, amongst others.

I also noticed that the _dqrng_ R code enables use of PCG64. Given that PCG32 requires a 64-bit seed, does this mean that PCG64 requires a 128-bit seed with `nwords=4`?

**Comment by rstub** [comment]
> Maybe a `dqset.stream` for those generators that support it, which would allow non-C++ users to take advantage of a key selling point of the PCG family, amongst others.

R-level support for parallel RNG usage is planned. With MT gone, all of RNGs exposed at the R level do support parallel operations of some sort. PCG has streams and jumps, Xo(ro)shiro has jumps and Threefry as counter-based engine is completely flexible in this regard. However, this flexibility is currently only supported when setting the full key or counter. Therefore it would make most sense to add an optional argument `stream=...` to `dqset.seed` and have a 

```
  virtual void seed(result_type seed, result_type stream)
```

in `random_64bit_generator`.  In `random_64bit_wrapper` this function would do nothing, but one could add appropriate template specialization for the supported RNGs.

That does not provide nice integration like `parallel` or `doRNG`, but would be a step in the right direction.


> I also noticed that the _dqrng_ R code enables use of PCG64. Given that PCG32 requires a 64-bit seed, does this mean that PCG64 requires a 128-bit seed with `nwords=4`?

PCG64 uses 128 bits of state and expects a `pcg128_t` on seeding. This is actually opposed to [RandomNumberEngine](https://en.cppreference.com/w/cpp/named_req/RandomNumberEngine) in C++11, where seeding is done with `result_type`, i.e. `uint64_t`. So right now PCG64 is seeded with 64 bits zero and 64 random bits. Similarly Threefry is seeded with 3 x 64 bits zero and 64 random bits. Since these RNGs have no problem with all zero states, this is not a "bad seed". This is slightly different for Xoroshiro128+ and Xoshiro256+. Both would be trapped in an all-zero state. Therefore the 64bit seed is used to seed SplitMix64 which then produces the initial state.

In all these cases the possible state space is not fully used. I do find 2^64 possible states sufficient at the moment, though. If it is found to be lacking, then it would make sense to seed from a `seed_sequence` filled from user input or R's RNG. At the moment all seeding goes via `random_64bit_generator`, which only supports a single `uint64_t`, though.
