### ISSUE TITLE
Additional multivariate distributions

### ISSUE THREAD

**Issue by statzhero** [daqana/dqrng#46]
Hello, do you plan to add any multivariate distributions for fast sampling? For example, such as `MASS::mvrnorm()`.

**Comment by kylebutts** [comment]
Here's a version of `mvrnorm` from the `{mvtnorm}` package (GPL-2 License, so we could add to `dqrng`?) A good chunk of the time is spent decomposing sigma (especially when `n` is small), but replacing `rnorm` with `dqrnorm`. Still a >2x speedup though.. Would you welcome a PR @rstub? 

```r
# From {mvtnorm} package with GPL-2 License
dqrmvnorm <- function(
    n, mean = rep(0, nrow(sigma)), sigma = diag(length(mean)),
    method = c("eigen", "svd", "chol"), checkSymmetry = TRUE
) {

  if (checkSymmetry && !isSymmetric(sigma,
    tol = sqrt(.Machine$double.eps),
    check.attributes = FALSE
  )) {
    stop("sigma must be a symmetric matrix")
  }
  if (length(mean) != nrow(sigma)) {
    stop("mean and sigma have non-conforming size")
  }

  method <- match.arg(method)

  R <- if (method == "eigen") {
    ev <- eigen(sigma, symmetric = TRUE)
    if (!all(ev$values >= -sqrt(.Machine$double.eps) * abs(ev$values[1]))) {
      warning("sigma is numerically not positive semidefinite")
    }
    ## ev$vectors %*% diag(sqrt(ev$values), length(ev$values)) %*% t(ev$vectors)
    ## faster for large  nrow(sigma):
    t(ev$vectors %*% (t(ev$vectors) * sqrt(pmax(ev$values, 0))))
  } else if (method == "svd") {
    s. <- svd(sigma)
    if (!all(s.$d >= -sqrt(.Machine$double.eps) * abs(s.$d[1]))) {
      warning("sigma is numerically not positive semidefinite")
    }
    t(s.$v %*% (t(s.$u) * sqrt(pmax(s.$d, 0))))
  } else if (method == "chol") {
    R <- chol(sigma, pivot = TRUE)
    R[, order(attr(R, "pivot"))]
  }

  # Generate MVNorm(0, sigma)
  retval <- matrix(dqrnorm(n * ncol(sigma)), nrow = n, byrow = TRUE) %*% R
  # Add in mean to make MVNorm(mean, sigma)
  retval <- sweep(retval, 2, mean, "+")
  
  colnames(retval) <- names(mean)
  retval
}
```

Here's a benchmark:
``` r
library(dqrng)

# From {mvtnorm} package with GPL-2 License
dqrmvnorm <- function(
    n, mean = rep(0, nrow(sigma)), sigma = diag(length(mean)),
    method = c("eigen", "svd", "chol"), checkSymmetry = TRUE
) {

  if (checkSymmetry && !isSymmetric(sigma,
    tol = sqrt(.Machine$double.eps),
    check.attributes = FALSE
  )) {
    stop("sigma must be a symmetric matrix")
  }
  if (length(mean) != nrow(sigma)) {
    stop("mean and sigma have non-conforming size")
  }

  method <- match.arg(method)

  R <- if (method == "eigen") {
    ev <- eigen(sigma, symmetric = TRUE)
    if (!all(ev$values >= -sqrt(.Machine$double.eps) * abs(ev$values[1]))) {
      warning("sigma is numerically not positive semidefinite")
    }
    ## ev$vectors %*% diag(sqrt(ev$values), length(ev$values)) %*% t(ev$vectors)
    ## faster for large  nrow(sigma):
    t(ev$vectors %*% (t(ev$vectors) * sqrt(pmax(ev$values, 0))))
  } else if (method == "svd") {
    s. <- svd(sigma)
    if (!all(s.$d >= -sqrt(.Machine$double.eps) * abs(s.$d[1]))) {
      warning("sigma is numerically not positive semidefinite")
    }
    t(s.$v %*% (t(s.$u) * sqrt(pmax(s.$d, 0))))
  } else if (method == "chol") {
    R <- chol(sigma, pivot = TRUE)
    R[, order(attr(R, "pivot"))]
  }

  # Generate MVNorm(0, sigma)
  retval <- matrix(dqrnorm(n * ncol(sigma)), nrow = n, byrow = TRUE) %*% R
  # Add in mean to make MVNorm(mean, sigma)
  retval <- sweep(retval, 2, mean, "+")
  
  colnames(retval) <- names(mean)
  retval
}

sigma <- matrix(c(1, 0.9, -0.3, 0.9, 1, -0.4, -0.3, -0.4, 1), ncol = 3)
mu <- c(10, 5, -3)

bench::mark(
  MASS::mvrnorm(1e4, mu, sigma),
  dqrmvnorm(1e4, mu, sigma),
  check = FALSE
)
#> # A tibble: 2 × 6
#>   expression                           min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 MASS::mvrnorm(10000, mu, sigma)   1.01ms    1.1ms      903.    1.55MB     21.9
#> 2 dqrmvnorm(10000, mu, sigma)      386.1µs  452.2µs     2187.    1.59MB     54.1

bench::mark(
  MASS::mvrnorm(1e6, mu, sigma),
  dqrmvnorm(1e6, mu, sigma),
  check = FALSE
)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
#> # A tibble: 2 × 6
#>   expression                           min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 MASS::mvrnorm(1e+06, mu, sigma)  110.7ms  136.1ms      7.84     114MB     18.8
#> 2 dqrmvnorm(1e+06, mu, sigma)       41.6ms   43.5ms     21.7      114MB     39.5
```

<sup>Created on 2023-07-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rstub** [comment]
Hi @kylebutts, Thanks, that looks interesting. Two things
* The relevant file in `{mvtnorm}` does not have a license header, c.f.  https://github.com/cran/mvtnorm/blob/master/R/mvnorm.R. This makes it difficult to know who should be added as copyright holder (most likely the maintainer Torsten Hothorn, @thothorn) and time.
* Does this belong in `{dqrng}` or would it make more sense to add an option in `{mvtnorm}` to optionally use `dqrnorm` (or `dqrunif` in other places)? It is mostly duplicated code otherwise. Or `mvtnorm::rmvnorm` could get an optional parameter for the `rnorm` like function to use. 

Both should be discussed with Torsten Hothorn. I am not sure if he will see this ping. If not, we will have to contact him directly.

**Comment by trafo-universe** [comment]
He somehow did see this ping :-)

mvtnorm 1.2-0 (on CRAN since ~ 4 weeks) has infrastructure for parameterisations in terms of the Cholesky of the covariance or precision matrices, mainly for computing probabilities but of course you also see speedups when sampling. The "lmvnorm_src" package vignette

https://cran.r-project.org/web/packages/mvtnorm/vignettes/lmvnorm_src.pdf

has all details, and you might want to start with an example in Section 2.14.

So far, I didn't change the "old" rmvnorm (because it's just two lines of code) but could maybe be convinced to do so.

Re licence:  This is GPL-2 and all authors (unless stated otherwise).

**Comment by rstub** [comment]
Thanks for chiming in! Most of the logic in `rmvnorm` is indeed about preparations. I would still prefer it to stay in your package. Would you be open to extend the signature like
```
rmvnorm <- function(n, mean = rep(0, nrow(sigma)), sigma = diag(length(mean)),
                    method=c("eigen", "svd", "chol"), pre0.9_9994 = FALSE,
                    checkSymmetry = TRUE, rnorm = stats::rnorm)
{
[rest unchanged]
}
```

This way a new `dqrmvnorm` could simply forward all arguments to `rmvnorm` and add `rnorm=dqrnorm`.

**Comment by trafo-universe** [comment]
OK. Done in 1.2-3 at R-forge, pls check. Will go live with the next CRAN update (in the 2nd half of August).

**Comment by statzhero** [comment]
Not right now but maybe others do. Thank you!On Jul 13, 2023, at 08:27, Ralf Stubner ***@***.***> wrote:﻿
Thanks! A quick first implementation looks good.
@statzhero Any other multivariate distributions you had in mind?

**Comment by rstub** [comment]
#51 providing `dqrmvnorm` has been merged. Closing this (for now).

**Comment by aadler** [comment]
Hi, you may want to look at the [mvnfast](https://cran.r-project.org/package=mvnfast) package which allows for faster multivariate normal/t draws.

**Comment by rstub** [comment]
Thanks for the pointer, @aadler. I wasn't aware of that package before. It looks like single core performance is quite similar with a slight edge for `dqrmvnorm`, probably due to the faster RNG. But the possibility to do parallel computing is of course nice. I will have to think about a way to integrate this.
